### ISSUE TITLE
WebSockets urn:ietf:params:xml:ns:xmpp-framing not supported

### ISSUE THREAD

**Issue by dreamersp** [node-xmpp/node-xmpp-server#106]
Greetings,
I'm trying to use node-xmpp-server with websockets but it seems that it doesn't implements the protocol for framing openning and closing as stated in point 3.4 of the RFC 7395 (http://tools.ietf.org/html/rfc7395#section-3.4).
The effect is that Strophe.js and any standard compliant client are unable to stablish a connection with websockets to a node-xmpp-server based WebSocket server.

Is there an easy/fast way of implementing urn:ietf:params:xml:ns:xmpp-framing in node-xmpp-server or are you planning to implement it soon?

Thanks a lot for such a straightforward xmpp server implementation by the way.
Regards.

**Comment by chris-rock** [comment]
I successfully used strophe websocket with node-xmpp-server. This is implemented in https://github.com/node-xmpp/radiowave/blob/master/lib/net/WsSocket.js. Code is identical, but not fully harmonized across the projects yet. What is the specific error you get?

**Comment by dreamersp** [comment]
It get's disconnected after a long waiting while saying just "Disconnected".
On the node-xmpp-server side it accounts for a connection, but never gets to authenticate event or anything else.
When setting env variable DEBUG=*, it logs the following:

  xmpp:server:websocket websocket connection +1s
  xmpp:server:websocket set socket +1ms
  xmpp:connection setup socket +0ms
  xmpp:connection use standard socket +1ms
  xmpp:connection setup stream +0ms
  xmpp:c2s:server new connection +1ms
  xmpp:server:websocket <open xmlns='urn:ietf:params:xml:ns:xmpp-framing' to='domain.com' version='1.0'/> +2ms
  xmpp:connection receive: <open xmlns='urn:ietf:params:xml:ns:xmpp-framing' to='domain.com' version='1.0'/> +0ms

I hope it helps.

**Comment by dreamersp** [comment]
Take note that I'm refering to Strophe.js v.1.2.0 and that it implements the final WebSockets XMPP specification, not the draft, and it states the use of `<open>` and `<close>` elements using the xmlns="urn:ietf:params:xml:ns:xmpp-framing".

**Comment by dreamersp** [comment]
Hi again,
I've checked WsSocket.js Radiowave's implementation that you referred against node-xmpp-server implementation and its basically the same: https://github.com/node-xmpp/node-xmpp-server/blob/master/lib/websocket/socket.js

So the problem must be the non interpretation of `<open>` `<close>` ws standard tags, don't you think?

**Comment by chris-rock** [comment]
We use the `WebSocketServer = require('ws').Server` ws module to do all web socket handling. We only work on top of that abstraction. Could you post a complete test case, that enables us to reproduce the same error?

**Comment by dreamersp** [comment]
Hi, using Strophe.js 1.2.0 or the new 1.2.2 (https://github.com/strophe/strophejs/blob/master/strophe.js), and trying to connect via ws://localhost:5280 to a local node-xmpp server with the sample server code in https://github.com/node-xmpp/node-xmpp-server/blob/master/examples/websocket_src.js, shows the error.
```
       var url = 'ws://localhost:5280/';
       var connection = new Strophe.Connection(url);
       connection.connect(username, password, connectHandler);

        connection.addHandler(messageHandler, null, 'message', 'chat');
        connection.addHandler(presenceHandler, null, 'presence', null);
        connection.addHandler(pingHandler, 'urn:xmpp:ping', 'iq', 'get');
       ...
```

Please note that Strophe.js tries to start the connection with `<open xmlns="urn:ietf:params:xml:ns:xmpp-framing" />` in compliance with the final XMPP over WebSockets RFC (http://tools.ietf.org/html/rfc7395#section-3.1).
It also fails to process the `<stream:features><mechanisms xmls="urn:ietf:params:xml:ns:xmpp-sasl">..`

As it must be written all prefixes or all namespaces, I fixed it in https://github.com/node-xmpp/node-xmpp-server/blob/master/lib/c2s/stream.js writing the element as `<features xmlns="http://etherx.jabber.org/streams">...`.

With several hacks into the stream_parser.js and connection.js code I introduced the `<open..>` tag management, but now I get a 'junk after document element' error in expat once the client (strophe.js) sends the `<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>...</auth>`.

**Comment by dreamersp** [comment]
Hi again, I managed to work out the "junk after document element", as the parser still assumes that the document may be still open, I had to expose the inner Parser reset function in sax_expat.js and call it from checkXMLHeader() in stream_parser.js to get it pass.

I had to modify several files involving several projects (node-xmpp-server, node-xmpp-core and ltx) to make it work in WebSockets as the RFC stands.

I consider most of the changes involving `<open...>` tag hacks, as they are messing and adding almost the same treatment as `<stream:stream ..` tag in stream_parser.js (this.parser.on('startElement'..), this.parser.on('endElement',..) (StreamParser.prototype.checkXMLHeader) ),  connection.js (Connection.prototype.startStream) and in ltx adding ```SaxExpat.prototype.reset = function() {
    this.parser.reset()
}``` in sax_expat.js.

However, as I need to have them all accessible by my development and deployment team, I'll publish this hacks in forks, that way it may also be more clear to follow and I hope we can reach a better solution.

**Comment by chris-rock** [comment]
Amazing. please go ahead and submit a PR.

**Comment by dreamersp** [comment]
Ok, already published and tested with ws:// protocol in:

https://github.com/dreamersp/node-xmpp-server
https://github.com/dreamersp/node-xmpp-core
https://github.com/dreamersp/ltx

I'll do pull requests immediately, but as I said, the changes are kind of a hack.
Next will be supporting wss:// (TLS over WS) protocol somehow.

**Comment by chris-rock** [comment]
take your time, let us know, when you are ready for a PR

**Comment by dreamersp** [comment]
Already done all three PRs.

**Comment by dreamersp** [comment]
Regarding TLS/HTTPS support with WebSockets, I added it on my fork of node-xmpp-server.
https://github.com/dreamersp/node-xmpp-server/blob/master/lib/websocket/server.js

Regards.

**Comment by sonnyp** [comment]
@dreamersp I had to implement WebSocket final RFC quickly on the refactor for work constraints; once we merge the refactor, I'll make sure to use your PR(s).

Here is how I did it https://github.com/node-xmpp/node-xmpp/commit/222db64ef007493c88f7ec6dc6a701f6ad20db18

I'm not really happy with it but it works and doesn't break anything.

I see 2 possibilities:

1) Split connection.js into StreamConnection and FrameConnection (kinda like what I started to do in the commit)

2) Make connection.js startStream smarter and allow to specify the node name and either to close the tag or not.

@chris-rock what do you think?

**Comment by sonnyp** [comment]
https://github.com/teambox/node-xmpp-server/commit/3834567261f0d26f923245e6f63623f6b17476d9
