### ISSUE TITLE
NGINX Proxy for XMPP Server

### ISSUE THREAD

**Issue by dapriett** [node-xmpp/node-xmpp-server#107]
Hello,

Is it possible to setup a proxy-pass in nginx to XMPP, on port 5222?  Can nginx load balance and handle TLS for nginx?

Thanks!

**Comment by chris-rock** [comment]
Hi @dapriett Generally, nginx is a great proxy for http traffic. Therefore you can use bosh and websocket with Nginx. Is this case nginx is able to do the TLS termination. For TCP I recommend using a proxy like haproxy.
