### ISSUE TITLE
Connection refused when authenticating

### ISSUE THREAD

**Issue by EricBorlandAC** [node-xmpp/node-xmpp-server#118]
Hi there,

First of all, thank you very much for this awesome module. We are building an app that uses a custom XMPP to synchronize and our server runs this module awesomely.
However, we have experienced lastly a problem while trying to connect after the server is live for few days. The point is that, after few days, the clients that are online don't experience any problem, but a new client that tries to connect receives a Connection Refused.

I know it sound like an external problem of this module and like a memory leak. the point is that we analyze it very deeply and the server has still 2GB of memory free and the CPU is lower than the 1%. Also an http server is running in the same machine and allows new users and logins without problem.
We have put a log in the authentication listener but nothing shows up there. The user tries to connect but the server does not receive anything, like if the authentication even was not properly fired by the xmpp-server module.

Have anyone experienced something like this? Anyone with any idea of how to resolve or to know more about this issue?
Btw we have tried with the last release and the same.

Thank you very much, I appreciate your work a lot.

Eric.

**Comment by sonnyp** [comment]
@EricBorlandAC what protocol are the clients using? BOSH ? WebSocket? TCP? are you using cluster?

**Comment by EricBorlandAC** [comment]
@sonnyp Sorry for the delay, I've been out for a couple of weeks. I am using the most simple configuration, with the TCP Server and without a cluster.
Thank you very much.

**Comment by sonnyp** [comment]
@EricBorlandAC I've made some internal changes. node-xmpp-server doesn't use node-expat anymore by default.
We've seen some issues with node-expat on production maybe it will fix yours.

Let me know.

**Comment by EricBorlandAC** [comment]
Okay, perfect. I'm updating the versions and if the problem persists i will let you know.

Thank you very much

**Comment by EricBorlandAC** [comment]
We haven't experienced this issue anymore since the last update. I close it now, if it happens again I will just reopen this issue.

Thank you all.
