### ISSUE TITLE
sometimes "online" event has received many time at time.

### ISSUE THREAD

**Issue by breaklee** [node-xmpp/node-xmpp-server#123]
sometime server socket received "online" event many times.

how can i handle this to one time?

and "reconnect" event is hot fired. is this available event?
(for example, i change network (wifi -> LTE or 3G), online event is fired, but not reconnect)

**Comment by sonnyp** [comment]
server do not reconnects

regarding the online event I'm not sure to follow, can you provide a code example?

**Comment by breaklee** [comment]
ah yes. i want to when reconnect event is fired.
but there are some issues when reconnect to true.
so, finally i decided to not using reconnect event.
