### ISSUE TITLE
TLS upgraded TCP connections are not released from lib/serverStop.js's connections Set

### ISSUE THREAD

**Issue by mdlavin** [node-xmpp/node-xmpp-server#139]
The lib/serverStop.js's connections Set is cleaned up by listening for the 'close' event <sup>1</sup> on the socket that is inserted into the Set.  However, when a TCP connection is upgraded to TLS some code in node-xmpp-core <sup>2</sup> removes all listeners to the 'close' event.  In heapdumps I have analysed, it does appear that TLS sockets remain in the serverStop cache and I believe the removed listener is the source of the trouble.

References
 1. https://github.com/node-xmpp/node-xmpp-server/blob/fe1d069afc5c16f075a86baa7f7ff1056a3f55bc/lib/serverStop.js#L19
 2. https://github.com/node-xmpp/node-xmpp-core/blob/a1eb7c1aca1b51b7aa39bb26d310c46d1b2436c8/lib/Connection.js#L314

**Comment by sonnyp** [comment]
thanks, nice find

Here is my proposal, I believe we shouldn't be using `removeAllListeners` (we don't want to remove listeners we didn't attached) and I would replace them with a `removeListener` per listener added.

@mdlavin what do you think?

**Comment by mdlavin** [comment]
I agree that switching from `removeAllListeners` to `removeListener` is a safer approach. I haven't debugged it enough to know if it will completely fix the leak, but it's a good start.  Did you have time/desire to attempt the fix, or would you like me to test out the idea?

**Comment by sonnyp** [comment]
@mdlavin if you could have a try at it that'd be great

**Comment by mdlavin** [comment]
Switching to `removeListener` does fix the leak for me.  Checkout the PR to see if you like the approach
