### ISSUE TITLE
Dialback secret is hardcoded

### ISSUE THREAD

**Issue by davidchiles** [node-xmpp/node-xmpp-server#140]
I don't understand why the dialback [secret](https://github.com/node-xmpp/node-xmpp-server/blob/master/lib/S2S/util/dialbackkey.js#L13) is hardcoded. 

From the [spec](http://xmpp.org/extensions/xep-0185.html):

> The Secret MUST either be set up in a configuration option for each host or process, or generated as a random string when starting the XMPP server. Creation of the Secret MUST NOT require communication between the Originating Server, the Authoritative Server, and optionally a third party (such as a database).

Would it make sense to generate this on startup?

**Comment by sonnyp** [comment]
> I don't understand why the dialback secret is hardcoded. 

I don't think there is any specific reason other than s2s not being a very active node-xmpp-server part.

> Would it make sense to generate this on startup?

Probably.

Feel free to PR

**Comment by davidchiles** [comment]
@sonnyp Thanks for the reply. I will get a PR together soon.
