### ISSUE TITLE
Node-xmpp-server

### ISSUE THREAD

**Issue by umasgn** [node-xmpp/node-xmpp-server#143]
I am developing a web-application which should support chat feature. Kindly, let me know if it is an alternate to ejabberd or library to connect node server to ejabberd. Also please let me know how can I use this server if it is presence server.

**Comment by sonnyp** [comment]
`node-xmpp-server` is a libray to build a node xmpp server

If you want to connect to an exisiting xmpp server you need an XMPP client.
For a Web based application I recommend stanza.io or xmpp-ftw.

As for the server you can use pretty much anything.
If you're looking for a Node.js XMPP server checkout https://github.com/node-xmpp/radiowave or https://github.com/sdelements/lets-chat XMPP server

**Comment by umasgn** [comment]
Hi sonnyp, thanks for quick reply, i'm struggling to decide which is the best way for developing a chat client just like whatsapp / wechat / telegram which complete functionality those apps have. i configured ejabberd server in our local server trying to learn things now. i'm a full stack developer (NodeJS) could you please suggest me which is the best way for developing this app.

**Comment by sonnyp** [comment]
take a look at what others do such as lets-chat, kaiwa and candy

**Comment by umasgn** [comment]
Thank you very much sonnyp
