### ISSUE TITLE
Stream object not deleted if referred in event handler, causing memory leaks

### ISSUE THREAD

**Issue by krnekit** [node-xmpp/node-xmpp-server#68]
When C2SStream object is referred in event handlers, it is not deleted on stream disconnect. Seems that closure still keeps reference to object, preventing it from destruction. To delete stream, one can assign it to `null`. Not sure, if it is proper behavior or memory leak.
This issue originally posted by @CrazyPandar in #61 I have done some research and simplified examples.

Server:
```js
var xmpp_server = require('node-xmpp-server')

var c2s = new xmpp_server.C2SServer({
    port: 5222,
    domain: 'localhost'
})

c2s.on('connect', function(client) {
    c2s.on('register', function(opts, cb) {
        cb(true)
    })

    client.on('authenticate', function(opts, cb) {
        return cb(null, opts)
    })

    client.on('online', function() {
        console.log('Online', client ? 1 : 0)   // Here 'client' object is referred
    })

    client.on('disconnect', function() {
        console.log('Disconnect')
        // Next statement removes reference to 'client' object and it could be destroyed
        // client = null
    })

})

setInterval(gc, 10000);
```
Server should be started with `--expose-gc`
Client:
```js
var xmpp_client = require('node-xmpp-client')
  , xmpp_core = require('node-xmpp-core')

var clients = {}
var clientsLeft = 0

function createClient(data) {
    var client = new xmpp_client.Client({
        jid: new xmpp_core.JID(null, 'chat', null),
        host: 'localhost',
        password: 'secret',
        preferred: 'ANONYMOUS'
    })

    client.connection.socket.on('error', function(err) {
        console.log('Socket error:', err)
        client.end()
    })

    client.on('error', function(err) {
        console.log('XMPP error:', err)
        client.end()
    })

    client.on('online', function(data) {
        clients[client.jid.resource] = client
        console.log('Connected', client.jid.toString(), 'current connections:', Object.keys(clients).length)
    })

    client.once('offline', function() {
        console.log('Disconnected', client.jid.toString(), 'current connections:', Object.keys(clients).length)
        delete clients[client.jid.resource]
    })

    if (--clientsLeft > 0) {
        setTimeout(createClient, 10)
    }
}

clientsLeft = parseInt(process.argv[2])

if (clientsLeft) {
    createClient()
}
```
The second command line argument for client should be number of connections.

Uncommenting `client = null` in server removes leak? but should it really be done this way?

**Comment by sonnyp** [comment]
Okay so the leak was actually a bug in the example.

Can you close this?

Also, ```client = null``` doesn't garbage collect ```client```. If there are other references to the object it won't work, if there is no other references to it then it's useless and might actually be harmful.

**Comment by lloydwatkin** [comment]
Yes agreed @sonnyp, but its a hint to gc to clean up, and given the example there were no other references :)
Can you make  PR to fix the example (if from this repo) please?

**Comment by chris-rock** [comment]
thanks @sonnyp and @lloydwatkin

**Comment by sonnyp** [comment]
@lloydwatkin I'm no v8 hacker but that I know of it is an urban legend.

The issue was already fixed in https://github.com/node-xmpp/node-xmpp-server/commit/8b6ae8f25ee9bcbfab8b24b8263035a87cf552df
